FROM alpine:3.22@sha256:14358309a308569c32bdc37e2e0e9694be33a9d99e68afb0f5ff33cc1f695dce

RUN apk add --no-cache privoxy && \
    echo "listen-address 0.0.0.0:8118" >> /etc/privoxy/config && \
    echo "forward-socks5 / warp-proxy:1080 ." >> /etc/privoxy/config

EXPOSE 8118

CMD ["privoxy", "--no-daemon", "--user", "privoxy", "/etc/privoxy/config"]
