FROM golang:1.26.4-alpine

ARG WARPPLUS_SOCKS=warpplus-us:1080

RUN apk add --no-cache privoxy && \
    printf '\nlisten-address 0.0.0.0:8118\nforward-socks5 / %s .\n' "$WARPPLUS_SOCKS" >> /etc/privoxy/config

EXPOSE 8118

CMD ["privoxy", "--no-daemon", "--user", "privoxy", "/etc/privoxy/config"]
